### ISSUE TITLE
能加上 gost么？

### ISSUE THREAD

**Issue by Miauson** [Aorp2008/Airp_sh#1]
能加上gost么
wget --no-check-certificate -O gost.sh https://raw.githubusercontent.com/KANIKIG/Multi-EasyGost/master/gost.sh && chmod +x gost.sh && ./gost.sh

**Comment by Aorp2008** [comment]
加了

**Comment by linbuxiao** [comment]
> 加了

gost 可以中转 hy2 的流量吗？

**Comment by Aorp2008** [comment]
> > 加了
> 
> gost 可以中转 hy2 的流量吗？
可以的

**Comment by Aorp2008** [comment]
> > 加了
> 
> gost 可以中转 hy2 的流量吗？

gost是直接转发 或者加密 不看内容的
